import type { LucideIcon } from "lucide-react";
import {
	Banknote,
	Bell,
	BookOpen,
	BookOpenText,
	Building2,
	Calendar,
	ChartColumn,
	ChartLine,
	ChartPie,
	ClipboardCheck,
	ClipboardList,
	Coins,
	FileCheck2,
	FileQuestion,
	FileText,
	GraduationCap,
	Home,
	Images,
	Landmark,
	Database,
	MessageSquareText,
	Layers,
	LayoutDashboard,
	Megaphone,
	NotebookPen,
	Presentation,
	Receipt,
	Settings,
	Trophy,
	User,
	UserCog,
	UserPlus,
	Users,
	Wallet,
} from "lucide-react";

export type RoleKey =
	| "siswa"
	| "orang-tua"
	| "tutor"
	| "admin-finance"
	| "admin-academic"
	| "owner";

/** Nama role di backend (tabel `roles`), dipakai untuk cek `user.roles.includes(...)`. */
export const ROLE_BACKEND_NAME: Record<RoleKey, string> = {
	siswa: "SISWA",
	"orang-tua": "ORANG_TUA",
	tutor: "TUTOR",
	"admin-finance": "ADMIN_FINANCE",
	"admin-academic": "ADMIN_ACADEMIC",
	owner: "OWNER",
};

export const ROLE_LABELS: Record<RoleKey, string> = {
	siswa: "Siswa",
	"orang-tua": "Orang Tua",
	tutor: "Tutor",
	"admin-finance": "Admin Finance",
	"admin-academic": "Admin Academic",
	owner: "Owner",
};

/** Kebalikan dari ROLE_BACKEND_NAME, dipakai untuk redirect setelah login. */
export const ROLE_KEY_BY_BACKEND_NAME: Record<string, RoleKey> =
	Object.fromEntries(
		(Object.entries(ROLE_BACKEND_NAME) as [RoleKey, string][]).map(
			([key, name]) => [name, key],
		),
	);

export interface NavItem {
	slug: string;
	label: string;
	icon: LucideIcon;
	/** [nav] = bottom nav utama mobile, [lainnya] = masuk drawer "Lainnya" (lihat docs/ROLE_PAGES.md). */
	placement: "nav" | "lainnya";
	/** Grup untuk heading sidebar desktop (menu besar). Item berurutan dengan group sama dirender di bawah satu heading. */
	group?: string;
}

/** Sumber: docs/ROLE_PAGES.md. Item pertama tiap role adalah Beranda/Dashboard (root path role). */
export const ROLE_NAV: Record<RoleKey, NavItem[]> = {
	siswa: [
		{ slug: "", label: "Beranda", icon: Home, placement: "nav" },
		{ slug: "jadwal", label: "Jadwal", icon: Calendar, placement: "nav" },
		{
			slug: "ujian",
			label: "Ujian",
			icon: FileCheck2,
			placement: "nav",
		},
		{ slug: "latsol", label: "Latsol", icon: NotebookPen, placement: "nav" },
		{
			slug: "feedback",
			label: "Feedback",
			icon: MessageSquareText,
			placement: "lainnya",
		},
		{
			slug: "performa",
			label: "Performa",
			icon: ChartLine,
			placement: "lainnya",
		},
		{
			slug: "ranking",
			label: "Ranking",
			icon: Trophy,
			placement: "lainnya",
		},
		{
			slug: "materi",
			label: "Materi",
			icon: BookOpen,
			placement: "lainnya",
		},
		{
			slug: "pengumuman",
			label: "Pengumuman",
			icon: Megaphone,
			placement: "lainnya",
		},
		{ slug: "profil", label: "Profil", icon: User, placement: "lainnya" },
	],
	"orang-tua": [
		{ slug: "", label: "Beranda", icon: Home, placement: "nav" },
		{
			slug: "pendaftaran",
			label: "Anak & Daftar",
			icon: Users,
			placement: "nav",
		},
		{
			slug: "pembayaran",
			label: "Pembayaran",
			icon: Wallet,
			placement: "nav",
		},
		{ slug: "jadwal", label: "Jadwal", icon: Calendar, placement: "nav" },
		{
			slug: "kehadiran",
			label: "Kehadiran",
			icon: ClipboardCheck,
			placement: "lainnya",
		},
		{
			slug: "feedback",
			label: "Feedback",
			icon: MessageSquareText,
			placement: "lainnya",
		},
		{
			slug: "program",
			label: "Program",
			icon: GraduationCap,
			placement: "lainnya",
		},
		{
			slug: "performa-anak",
			label: "Performa Anak",
			icon: ChartLine,
			placement: "lainnya",
		},
		{
			slug: "ranking",
			label: "Ranking Siswa",
			icon: Trophy,
			placement: "lainnya",
		},
		{
			slug: "pengumuman",
			label: "Pengumuman",
			icon: Megaphone,
			placement: "lainnya",
		},
		{ slug: "profil", label: "Profil", icon: User, placement: "lainnya" },
	],
	tutor: [
		{
			slug: "",
			label: "Beranda",
			icon: Home,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "kelompok",
			label: "Kelompok",
			icon: Users,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "jadwal-sesi",
			label: "Jadwal/Sesi",
			icon: Calendar,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "absensi",
			label: "Absensi",
			icon: ClipboardCheck,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "feedback",
			label: "Feedback",
			icon: MessageSquareText,
			placement: "lainnya",
			group: "Utama",
		},
		{
			slug: "latsol",
			label: "Latsol",
			icon: NotebookPen,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "ujian",
			label: "Ujian",
			icon: FileCheck2,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "nilai",
			label: "Nilai",
			icon: ClipboardList,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "pembahasan",
			label: "Pembahasan",
			icon: BookOpenText,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "ranking",
			label: "Ranking Siswa",
			icon: Trophy,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "materi",
			label: "Materi",
			icon: BookOpen,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "soal",
			label: "Soal",
			icon: FileQuestion,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "pustaka",
			label: "Pustaka Gambar",
			icon: Images,
			placement: "lainnya",
			group: "Akademik",
		},
		{
			slug: "notifikasi",
			label: "Notifikasi",
			icon: Bell,
			placement: "lainnya",
			group: "Akun",
		},
		{
			slug: "profil",
			label: "Profil & Status Kepegawaian",
			icon: User,
			placement: "lainnya",
			group: "Akun",
		},
	],
	"admin-finance": [
		{
			slug: "",
			label: "Dashboard",
			icon: LayoutDashboard,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "siswa",
			label: "Siswa",
			icon: Users,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "orang-tua",
			label: "Orang Tua",
			icon: UserPlus,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "pendaftaran",
			label: "Pendaftaran",
			icon: ClipboardList,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "kelompok",
			label: "Kelompok",
			icon: Users,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "invoice",
			label: "Invoice",
			icon: FileText,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "transaksi-harian",
			label: "Transaksi Harian",
			icon: Landmark,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "pembayaran",
			label: "Pembayaran",
			icon: Wallet,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "bukti",
			label: "Bukti",
			icon: Receipt,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "piutang",
			label: "Penagihan & Reminder",
			icon: Banknote,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "kas-bank",
			label: "Kas/Bank",
			icon: Landmark,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "pustaka",
			label: "Pustaka Media",
			icon: Images,
			placement: "lainnya",
			group: "Transaksi",
		},
		{
			slug: "rab",
			label: "RAB",
			icon: ChartColumn,
			placement: "lainnya",
			group: "Anggaran & SDM",
		},
		{
			slug: "pengeluaran",
			label: "Pengeluaran",
			icon: Banknote,
			placement: "lainnya",
			group: "Anggaran & SDM",
		},
		{
			slug: "payroll",
			label: "Gaji Bulanan Tutor",
			icon: Coins,
			placement: "lainnya",
			group: "Anggaran & SDM",
		},
		{
			slug: "laporan",
			label: "Laporan",
			icon: ChartPie,
			placement: "lainnya",
			group: "Sistem",
		},
		{
			slug: "pengaturan",
			label: "Pengaturan",
			icon: Settings,
			placement: "lainnya",
			group: "Sistem",
		},
		{
			slug: "akun",
			label: "Manajemen Akun",
			icon: UserCog,
			placement: "lainnya",
			group: "Sistem",
		},
		{
			slug: "notifikasi",
			label: "Notifikasi",
			icon: Bell,
			placement: "lainnya",
			group: "Sistem",
		},
		{
			slug: "profil",
			label: "Profil",
			icon: User,
			placement: "lainnya",
			group: "Sistem",
		},
	],
	"admin-academic": [
		{
			slug: "",
			label: "Dashboard",
			icon: LayoutDashboard,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "program",
			label: "Program",
			icon: GraduationCap,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "kelompok",
			label: "Kelompok",
			icon: Users,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "level",
			label: "Level",
			icon: Layers,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "pendaftaran",
			label: "Pendaftaran",
			icon: ClipboardList,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "tutor",
			label: "Tutor",
			icon: Presentation,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "jadwal",
			label: "Jadwal & Sesi",
			icon: Calendar,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "fasilitas",
			label: "Fasilitas",
			icon: Building2,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "absensi",
			label: "Absensi",
			icon: ClipboardCheck,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "master-data",
			label: "Master Data",
			icon: Database,
			placement: "lainnya",
			group: "Struktur",
		},
		{
			slug: "materi",
			label: "Materi",
			icon: BookOpen,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "soal",
			label: "Soal",
			icon: FileQuestion,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "latsol",
			label: "Latsol",
			icon: NotebookPen,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "ujian",
			label: "Ujian",
			icon: FileCheck2,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "pembahasan",
			label: "Pembahasan",
			icon: BookOpenText,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "pustaka",
			label: "Pustaka Gambar",
			icon: Images,
			placement: "lainnya",
			group: "Konten & Ujian",
		},
		{
			slug: "analisis",
			label: "Analisis",
			icon: ChartLine,
			placement: "lainnya",
			group: "Insight",
		},
		{
			slug: "ranking",
			label: "Ranking",
			icon: Trophy,
			placement: "lainnya",
			group: "Insight",
		},
		{
			slug: "laporan",
			label: "Laporan",
			icon: ChartPie,
			placement: "lainnya",
			group: "Insight",
		},
		{
			slug: "pengaturan",
			label: "Pengaturan",
			icon: Settings,
			placement: "lainnya",
			group: "Akun",
		},
		{
			slug: "akun",
			label: "Manajemen Akun",
			icon: UserCog,
			placement: "lainnya",
			group: "Akun",
		},
		{
			slug: "notifikasi",
			label: "Notifikasi",
			icon: Bell,
			placement: "lainnya",
			group: "Akun",
		},
		{
			slug: "profil",
			label: "Profil",
			icon: User,
			placement: "lainnya",
			group: "Akun",
		},
	],
	owner: [
		{
			slug: "",
			label: "Dashboard KPI",
			icon: LayoutDashboard,
			placement: "nav",
			group: "Utama",
		},
		{
			slug: "laporan",
			label: "Laporan",
			icon: ChartPie,
			placement: "nav",
			group: "Laporan",
		},
		{
			slug: "piutang",
			label: "Piutang",
			icon: Banknote,
			placement: "lainnya",
			group: "Laporan",
		},
		{
			slug: "rab-vs-actual",
			label: "RAB vs Actual",
			icon: ChartColumn,
			placement: "lainnya",
			group: "Laporan",
		},
		{
			slug: "bukti",
			label: "Bukti Pembayaran",
			icon: FileCheck2,
			placement: "lainnya",
			group: "Laporan",
		},
		{
			slug: "notifikasi",
			label: "Notifikasi",
			icon: Bell,
			placement: "lainnya",
			group: "Sistem",
		},
		{
			slug: "profil",
			label: "Profil",
			icon: User,
			placement: "lainnya",
			group: "Sistem",
		},
	],
};

export function findNavItem(role: RoleKey, slug: string): NavItem | undefined {
	return ROLE_NAV[role].find((item) => item.slug === slug);
}
